import{a as u,S as f,i}from"./assets/vendor-Cq7ZUixy.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function m(o){const s="https://pixabay.com/api/",a={params:{key:"54246352-35184811c7b33f51a38e3c8ed",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:9}};return u.get(s,a).then(e=>e.data).catch(e=>{throw console.error("Error fetching images:",e),e})}let p=new f(".gallery a",{captionsData:"alt",captionDelay:250});const l=document.querySelector(".gallery"),d=document.querySelector(".loader-container");function h(o){const s=o.map(r=>`<li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
            <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
        <div class="info-item"><b>Likes</b><span>${r.likes}</span></div>
        <div class="info-item"><b>Views</b><span>${r.views}</span></div>
        <div class="info-item"><b>Comments</b><span>${r.comments}</span></div>
        <div class="info-item"><b>Downloads</b><span>${r.downloads}</span></div>
        </div>
</li>`).join("");l.insertAdjacentHTML("beforeend",s),p.refresh()}function y(){l.innerHTML=""}const g=()=>d.classList.remove("is-hidden"),b=()=>d.classList.add("is-hidden"),c=document.querySelector(".form");c.addEventListener("submit",o=>{o.preventDefault();const s=o.target.elements["search-text"].value.trim();if(s===""){i.error({message:"Please enter search query."});return}y(),g(),m(s).then(r=>{if(r.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(r.hits)}).catch(r=>{i.error({message:"Something went wrong!"})}).finally(()=>{b(),c.reset()})});
//# sourceMappingURL=index.js.map
